### ISSUE TITLE
Consider removing the text comparison piece.

### ISSUE THREAD

**Issue by saroup** [microsoft/NLU.DevOps#253] opened 2020-02-12 16:06 UTC
We think that it may not make lots of sense to test for entities with ASR.

- how do we handle entities that are likely misspelled by ASR?
> The batch testing has a labeled set of utterances to compare with, and both the testing and training need to be of the same data that is used. In turn if this is a pipeline that follows from ASR as the only source then the utterances should be those after ASR, and not textual that are perfect. In turn this wouldn’t be an issue. It is more of an issue with the model being trained with generated data that doesn’t have speech errors, and using ASR ahead. Using the ASR output would be measuring something else other than performance.

**Comment by rozele** [comment] 2020-02-14 19:07
This is a dupe of #247.

**Closed by rozele** 2020-02-14 19:07 UTC
